{
 "title": "Lending_club",
 "time": { "from": "2010-12-31T18:30:00.000Z", "to": "2019-12-31T18:29:59.000Z" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "state",
    "query": "SELECT DISTINCT addr_state FROM lending_club_loans ORDER BY 1;"
   },
   {
    "name": "grade",
    "query": "SELECT DISTINCT grade FROM lending_club_loans ORDER BY 1;"
   }
  ]
 },
 "panels": [
  {
   "title": "Lending Velocity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  date_trunc('month', issue_d::timestamp) AS \"time\",\r\n  sum(funded_amnt::numeric) as \"Monthly Funded\",\r\n  (sum(funded_amnt::numeric) - lag(sum(funded_amnt::numeric)) OVER (ORDER BY date_trunc('month', issue_d::timestamp))) \r\n    / NULLIF(lag(sum(funded_amnt::numeric)) OVER (ORDER BY date_trunc('month', issue_d::timestamp)), 0) * 100 as \"Growth %\"\r\nFROM lending_club_loans\r\nGROUP BY 1\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Grade Wise Total Loan Amounts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  date_trunc('month', issue_d::timestamp) AS \"time\",\r\n  grade,\r\n  sum(loan_amnt::numeric) AS \"Total Amount\"\r\nFROM lending_club_loans \r\nWHERE $__timeFilter(issue_d::timestamp)\r\nGROUP BY 1,2\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "State wise ownership",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  addr_state AS \"state\",\r\n  home_ownership,\r\n  count(*) AS \"Count\"\r\nFROM lending_club_loans\r\nWHERE addr_state IN ($state)\r\nGROUP BY 1, 2\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Regional Exposure",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  addr_state AS \"state\",\r\n  sum(loan_amnt::numeric) AS \"Value\",\r\n  count(*) AS \"Volume\"\r\nFROM lending_club_loans \r\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Average Rate vs Default rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('year', issue_d::timestamp) AS \"time\", \r\n       avg(int_rate::numeric) as \"Avg Rate\",\r\n       (count(*) FILTER (WHERE is_default = '1')::numeric / count(*)) * 100 as \"Default %\"\r\nFROM lending_club_loans\r\nWHERE $__timeFilter(issue_d::timestamp)\r\nGROUP BY 1 ORDER BY 1"
    }
   ]
  },
  {
   "title": "Grade wise loans",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  date_trunc('month', issue_d::timestamp) AS \"time\",\r\n  grade,\r\n  sum(loan_amnt::numeric) AS \"Total Amount\"\r\nFROM lending_club_loans \r\nWHERE $__timeFilter(issue_d::timestamp)\r\nGROUP BY 1,2\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Default Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT (count(*) FILTER (WHERE is_default = '1')::numeric / count(*)) * 100 FROM lending_club_loans"
    }
   ]
  },
  {
   "title": "Average rate of interest",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT avg(int_rate::numeric) FROM lending_club_loans"
    }
   ]
  },
  {
   "title": "Total Loan Amount",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 7, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(loan_amnt::numeric) FROM lending_club_loans"
    }
   ]
  },
  {
   "title": "Average Borrower Income",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT avg(annual_inc::numeric) FROM lending_club_loans"
    }
   ]
  }
 ]
}